[2022-10-04 15:34:10,405] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2022-09-07T04:05:38.122327+00:00 [queued]>
[2022-10-04 15:34:10,438] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2022-09-07T04:05:38.122327+00:00 [queued]>
[2022-10-04 15:34:10,440] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 15:34:10,442] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-10-04 15:34:10,446] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 15:34:10,548] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2022-09-07 04:05:38.122327+00:00
[2022-10-04 15:34:10,569] {standard_task_runner.py:52} INFO - Started process 5569 to run task
[2022-10-04 15:34:10,616] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'td-dag-test', 'get_data', 'manual__2022-09-07T04:05:38.122327+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/td_dag_test.py', '--cfg-path', '/tmp/tmp2n8_mmk9', '--error-file', '/tmp/tmpyvuxru1b']
[2022-10-04 15:34:10,648] {standard_task_runner.py:80} INFO - Job 191: Subtask get_data
[2022-10-04 15:34:11,211] {task_command.py:371} INFO - Running <TaskInstance: td-dag-test.get_data manual__2022-09-07T04:05:38.122327+00:00 [running]> on host f2e7b0d61203
[2022-10-04 15:34:11,948] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=mravelo@groupon.com
AIRFLOW_CTX_DAG_OWNER=FSA
AIRFLOW_CTX_DAG_ID=td-dag-test
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-07T04:05:38.122327+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-07T04:05:38.122327+00:00
[2022-10-04 15:34:11,982] {logging_mixin.py:115} INFO - --- INFO: Move data process started ---
[2022-10-04 15:34:12,012] {base.py:68} INFO - Using connection ID 'teradata' for task execution.
[2022-10-04 15:34:39,826] {logging_mixin.py:115} INFO - we came back from Teradata
[2022-10-04 15:34:39,846] {logging_mixin.py:115} INFO -     environment_id  ...     last_modified_by
0           10001  ...  EMERGENOW\brobinson
1               1  ...  EMERGENOW\brobinson
2           20001  ...  EMERGENOW\brobinson

[3 rows x 17 columns]
[2022-10-04 15:34:39,847] {logging_mixin.py:115} INFO - --- INFO: Move data process complete ---
[2022-10-04 15:34:39,849] {logging_mixin.py:115} INFO - --- INFO: CSV file created ---
[2022-10-04 15:34:39,858] {python.py:173} INFO - Done. Returned value was: None
[2022-10-04 15:34:39,870] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=td-dag-test, task_id=get_data, execution_date=20220907T040538, start_date=20221004T153410, end_date=20221004T153439
[2022-10-04 15:34:40,015] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-04 15:34:40,053] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
