[2022-10-04 15:34:12,095] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2022-09-07T03:44:58.725145+00:00 [queued]>
[2022-10-04 15:34:12,133] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2022-09-07T03:44:58.725145+00:00 [queued]>
[2022-10-04 15:34:12,134] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 15:34:12,136] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-10-04 15:34:12,139] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 15:34:12,179] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2022-09-07 03:44:58.725145+00:00
[2022-10-04 15:34:12,260] {standard_task_runner.py:52} INFO - Started process 5628 to run task
[2022-10-04 15:34:12,385] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'td-dag-test', 'get_data', 'manual__2022-09-07T03:44:58.725145+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/td_dag_test.py', '--cfg-path', '/tmp/tmpp5hwp4ah', '--error-file', '/tmp/tmpom1df9ls']
[2022-10-04 15:34:12,415] {standard_task_runner.py:80} INFO - Job 194: Subtask get_data
[2022-10-04 15:34:13,087] {task_command.py:371} INFO - Running <TaskInstance: td-dag-test.get_data manual__2022-09-07T03:44:58.725145+00:00 [running]> on host f2e7b0d61203
[2022-10-04 15:34:13,634] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=mravelo@groupon.com
AIRFLOW_CTX_DAG_OWNER=FSA
AIRFLOW_CTX_DAG_ID=td-dag-test
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-07T03:44:58.725145+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-07T03:44:58.725145+00:00
[2022-10-04 15:34:13,653] {logging_mixin.py:115} INFO - --- INFO: Move data process started ---
[2022-10-04 15:34:13,757] {base.py:68} INFO - Using connection ID 'teradata' for task execution.
[2022-10-04 15:34:23,624] {local_task_job.py:221} WARNING - State of this instance has been externally set to None. Terminating instance.
[2022-10-04 15:34:23,665] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 5628. PIDs of all processes in the group: [5628]
[2022-10-04 15:34:23,683] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 5628
[2022-10-04 15:34:26,927] {process_utils.py:75} INFO - Process psutil.Process(pid=5628, status='terminated', exitcode=<Negsignal.SIGABRT: -6>, started='15:34:12') (5628) terminated with exit code Negsignal.SIGABRT
