[2023-01-09 17:25:56,774] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2023-01-09T17:25:49.823205+00:00 [queued]>
[2023-01-09 17:25:56,888] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2023-01-09T17:25:49.823205+00:00 [queued]>
[2023-01-09 17:25:56,890] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-09 17:25:56,894] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-01-09 17:25:56,897] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-09 17:25:57,044] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2023-01-09 17:25:49.823205+00:00
[2023-01-09 17:25:57,082] {standard_task_runner.py:52} INFO - Started process 349 to run task
[2023-01-09 17:25:57,108] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'td-dag-test', 'get_data', 'manual__2023-01-09T17:25:49.823205+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/td_dag_test.py', '--cfg-path', '/tmp/tmpbkao5w_k', '--error-file', '/tmp/tmp1d9xo0zf']
[2023-01-09 17:25:57,113] {standard_task_runner.py:80} INFO - Job 206: Subtask get_data
[2023-01-09 17:25:57,408] {task_command.py:371} INFO - Running <TaskInstance: td-dag-test.get_data manual__2023-01-09T17:25:49.823205+00:00 [running]> on host f44165fb6ebe
[2023-01-09 17:25:57,762] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=FSA
AIRFLOW_CTX_DAG_ID=td-dag-test
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-09T17:25:49.823205+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-09T17:25:49.823205+00:00
[2023-01-09 17:25:57,766] {logging_mixin.py:115} INFO - --- INFO: Move data process started ---
[2023-01-09 17:25:57,798] {base.py:68} INFO - Using connection ID 'teradata' for task execution.
[2023-01-09 17:26:01,124] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGILL
[2023-01-09 17:26:01,237] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=td-dag-test, task_id=get_data, execution_date=20230109T172549, start_date=20230109T172556, end_date=20230109T172601
[2023-01-09 17:26:01,360] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
